
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.7  # Use the ref you want to point at
    hooks:
      - id: uv-lock      # keep uv.lock in sync
      - id: uv-export    
        args: [--extra=dev, --output-file=requirements-dev.txt]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files 
