[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#fb4f14"  # Broncos orange
backgroundColor="#121212"  # Dark background
secondaryBackgroundColor="#1E1E1E"  # Slightly lighter for cards
textColor="#E0E0E0"  # Light text

[theme.sidebar]
backgroundColor="#1E1E1E"
secondaryBackgroundColor="#2A2A2A"
textColor="#E0E0E0"
